task: text classification
type: rnn
rnn_cell: lstm
model_name: rnn_lstm_description_emb_256
train_corpus_path: assets/languagecorpora/french_corpus.txt
#pretrained_model_path: saved/models/rnn/title_128_rnn
data:
  training_file: assets/trainingdata/rakuten_train.csv
  test_file: assets/trainingdata/rakuten_test.csv
  category_mapping: assets/trainingdata/rakuten_category_map
  no_labels: 27
  concat_columns: true
  text_columns:
    - Description
  category_column: Category
  category_map: assets/trainingdata/rakuten_category_map
  language: french
rnn_layer_sizes:
  - 128
  - 128
dense_layer_sizes:
  - 128
  - 32
epochs: 10
#word_embeddings: fasttext
word_embedding_size: 256
#word_embedding_save_path: saved/models/fasttext/french_corpus_ecommerce_128/
language: french
optimizer: 'adam'
batch_size: 128
loss: 'categorical_crossentropy'
save_path: saved/models/rnn/description_256_rnn_lstm



