DEFAULT_IMAGE_SIZE = 128
DEFAULT_NO_CLASSES = 1000
DEFAULT_NO_CHANNELS = 3

DEFAULT_IMAGE_INPUT_RAW_SUFFIX = 'image_input_raw'

DEFAULT_BATCH_SIZE = 128
DEFAULT_NO_EPOCHS = 20

DEFAULT_LOGS_FOLDER = 'logs'
DEFAULT_MODELS_FOLDER = 'models'

DEFAULT_NO_WORKERS = 5

DEFAULT_WORD2VEC_WINDOW_SIZE = 5
DEFAULT_WORD2VEC_MIN_COUNT = 1
DEFAULT_WORD2VEC_EMBEDDING_SIZE = 128
DEFAULT_WORD2VEC_SAVE_PATH = 'saved/models/text/word2vec/'
DEFAULT_WORD2VEC_NO_EPOCHS = 5


DEFAULT_FASTTEXT_WINDOW_SIZE = 5
DEFAULT_FASTTEXT_MIN_COUNT = 1
DEFAULT_FASTTEXT_EMBEDDING_SIZE = 128
DEFAULT_FASTTEXT_SAVE_PATH = 'saved/models/text/fasttext/'
DEFAULT_FASTTEXT_NO_EPOCHS = 5

DEFAULT_TEXT_INPUT_RAW_SUFFIX = 'text_input_raw'
DEFAULT_TEXT_ENCODING_LAYER_SUFFIX = 'text_vectorization_layer'
DEFAULT_EMBEDDING_LAYER_SUFFIX = 'embedding_layer'
DEFAULT_EMBEDDING_NAME = 'no_name'

DEFAULT_RNN_MODEL_NAME = 'rnn_model'
DEFAULT_RNN_LAYER_NAME = 'rnn_layer'


DEFAULT_FEATURES_LAYER_NAME = 'feature_layer'
DEFAULT_CLASSIFIER_NAME = 'classifier'
DEFAULT_CLASSIFIER_INPUT = 'classifier_input'
DEFAULT_CLASSIFIER_ACTIVATION_FUNCTION = 'sigmoid'
DEFAULT_CLASSIFIER_DENSE_LAYER = 'classifier_dense'
DEFAULT_CLASSIFIER_SOFTMAX_LAYER = 'classifier_softmax'
DEFAULT_CLASSIFIER_FUNCTIONAL_LAYER = 'classifier'
