task: text classification
type: rnn
rnn_cell: lstm
model_name: rnn_lstm_title_128_high_amazon
train_corpus_path: assets/languagecorpora/french_corpus.txt
#pretrained_model_path: saved/models/rnn/title_256_rnn
data:
  training_file: /Users/cipri/PycharmProjects/createAllShops/amazon_train.csv
  test_file: /Users/cipri/PycharmProjects/createAllShops/amazon_test.csv
  category_mapping: /Users/cipri/PycharmProjects/createAllShops/cat_map.txt
  no_labels: 25
  concat_columns: true
  text_columns:
    - title
  category_column: category
  category_map: /Users/cipri/PycharmProjects/createAllShops/cat_map.txt
  language: english
rnn_layer_sizes:
  - 256
dense_layer_sizes:
  - 128
  - 32
epochs: 10
#word_embeddings: fasttext
word_embedding_size: 128
#word_embedding_save_path: saved/models/fasttext/french_corpus_ecommerce_128/
language: french
optimizer: 'adam'
batch_size: 128
loss: 'categorical_crossentropy'
save_path: saved/models/rnn/title_128_rnn_lstm_high_amazon



