task: text classification
type: rnn
rnn_cell: lstm
model_name: rnn_lstm_model
train_corpus_path: assets/trainingdata/french_corpus_ecommerce
#pretrained_model_path: saved/models/rnn/title_256_rnn
data:
  training_file: assets/trainingdata/rakuten_train.csv
  test_file: assets/trainingdata/rakuten_test.csv
  category_mapping: assets/trainingdata/rakuten_category_map
  no_labels: 27
  concat_columns: true
  text_columns:
    - Title
  category_column: Category
  category_map: assets/trainingdata/rakuten_category_map
  language: french
rnn_layer_sizes:
  - 128
  - 128
dense_layer_sizes:
  - 128
  - 32
epochs: 1
#word_embeddings: word2vec
word_embedding_size: 128
#word_embedding_save_path: saved/models/word2vec/french_corpus_ecommerce/
language: french
optimizer: 'adam'
batch_size: 128
loss: 'categorical_crossentropy'
save_path: saved/models/rnn/title_128_rnn



