task: multimodal classification
data:
  training_file: assets/trainingdata/rakuten_train.csv
  test_file: assets/trainingdata/rakuten_test.csv
  inference_file: assets/trainingdata/rakuten_test.csv
  inference_results: results/rakuten_inference_results.csv
  category_column: Category
  category_map: assets/trainingdata/rakuten_category_map
  language: french
  images_path:
modes:
  - model: saved/models/rnn/title_128_rnn
    is_feature_extractor: false
    type: text
    data_column: Title
  - model: saved/models/doc2vec/title_doc2vec
    is_feature_extractor: false
    type: text
    data_column: Title
epochs: 1
batch_size: 128
save_path: saved/models/multimodal/titleRnn_titledoc2vec
